### ISSUE TITLE
[Fullstack] Match Project Plan Component To The Figma

### ISSUE THREAD

**Issue by tawsifkamal** [GTBitsOfGood/southface#67]
### Description
As a developer, I want to be able to add a standard to my project plan from the library page, and then see the updated project plan on the project plan view page. I want to be able to add the project plan both on the standard library view by clicking Add To Plan as well on the modal view by clicking Add To Plan.

Currently, the StandardCardTable component is shown also in the Project Plan Builder (PPB) Page. This should not be the case since in the design, the cards and search functionality are not shown on the PPB page. If users would like to add more standards to the plan they will be able to do so from the library page or by clicking on "view recent standards" which will be implemented later on.

For the frontend, match only this part of the project plan from the design to the actual code:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/214360632-3f3e1def-c905-448b-b59b-e30d81db11fc.png">

Use the existing logic for naming, downloading, printing, ending project plan, etc. However, do add the logic on the library page for the "add to plan" buttons (both on library view + modal view) so that it adds that specific standard to the project plan (the database will need to be modified, possibly the schema as well). Additionally, since the userId property already exists on the project plan schema, ensure that based on whoever is logged in, it will show the accurate project plans.

The standard card component is being wrapped by other props in the project plan page and thus is not allowing the component to be used across the library and project plan page. Refactor the standard card component so that it could be used across both pages and additionally the shopping cart view. + recent standards view. The following are the areas where the card component is being used:

#### Library Page
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/214127091-43ed833a-f3de-4c59-8b83-ebf6a7898d84.png">

#### Shopping Cart View 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/214127319-846f145b-334b-4a2f-93cd-129f457568ca.png">

#### Project Plan Builder Page
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/214127482-cc1c7269-6b17-4be0-8546-42448c181cc0.png">

#### Recent Standards View 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/214127579-a9b8a483-6db7-4cf1-b9e7-848d22954226.png">

### Acceptance Criteria
- [x] StandardCardLibrary Component + search bar is deleted on PPB page.
- [ ] Add To Plan functionality works from /library to project plan page (database modified, on-refresh, user-specific, etc)
- [ ] The Frontend of the PPB (that specific portion shown in the image) matches the figma design
- [ ] Accurate project plans are shown for each user
- [ ] The card component is able to be used across the library page + project plan builder page and is future proof to be used on shopping cart view + recent standards view.

### Other Notes
- currently, there is no button called "Add To Plan" on Standard Card. It is only there in modal view. For now, just add a simple button (don't worry about styling) in the standard card in order to flesh out this Add To Plan functionality.
- If you are not able to refactor the card so that it is usable across all components, don't worry it will be saved for a later sprint. Focus more on matching the figma + logic of adding to plan.
- See the [figma flow](https://www.figma.com/proto/YTJqtLkjyxYdS3UkfR9dza/Southface-%2F-Fall22?node-id=565%3A774&starting-point-node-id=565%3A774).
