### ISSUE TITLE
[Frontend] Project Plan Non-Edit/Edit View W/ Figma

### ISSUE THREAD

**Issue by tawsifkamal** [GTBitsOfGood/southface#80]
### Description
Now that most of the functionality is added, match all the related styles for the non-edit and edit view for the project plan builder with the figma.

**Edit View**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/217166684-4d70f8f3-7871-46c9-b5be-900867eaa711.png">

**Non-Edit View**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/217166813-020f74d9-08c4-4a48-9482-ec1f344e512c.png">

### Acceptance Criteria
**Non-Edit View**
- [ ] color schemes match (remove button is red, edit button is grey, etc)
- [ ] overflow scroll property is added if the project plan overflows with too many standards
- [ ] spacing is consistent across large and extra large screen sizes

**Edit View**
- [ ] "X" button matches
- [ ] "Add" button matches
- [ ] deselected images are greyed out appropriately

**After Clicking Save Changes*8
- [ ] Changes saved tag is shown

### Other Notes
- don't worry too much about any crazy edge cases except the overflow scroll right now for the entire project plan
- for spacing related issues, look into the large and extra large screen sizes found on chakra design system
