### ISSUE TITLE
[Fullstack] Search Bar + Display Accurate Cards

### ISSUE THREAD

**Issue by tawsifkamal** [GTBitsOfGood/southface#99]
### Description
As a user (general, admin, or logged out), I want to be able to search both from each primary category page, or building type page (see pictures below). Additionally, I want to see the accurate cards for each primaryCategory and BuildingType.

**Part 1**
Right now, the search happens continuously as you type. This is really bad since we are making a database call for each value typed in on the search bar. Make it so that it performs the search operation ONLY when you click the search button. Additionally, I want to be able to search from both the building type and primary category pages.

Don't implement the filter selection part of the search bar. This is being worked on this ticket so don't worry about it.

**Part 2**
The cards that are being rendered right now are not filtered for a building type or primary category. So for example, a card that is of building type "commercial" and primary category "site planning" is being displayed on every single building type and and every single primary category. Make it so that that card would only be displayed when you navigate to Commercial -> Site-Planning.

**Search Bar on buildingtype page**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/220452969-21cb09ea-d784-4e08-a83f-5cfc83c291a3.png">

**Search Bar on primary category page**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/220453097-36c73ab1-364a-4908-b111-9b3111a9a2c7.png">

#### Part 1
**Frontend**
- [x] Search Bar frontend matches figma (input + search button) 
- [x] Filter Button is added (Frontend matches) but onClick does nothing (logic is being worked on this sprint)

**Backend**
- [ ] Search on BuildingType page searches for any matches where buildingType of card == the current building type (see other notes)
- [ ] Search on PrimaryCategory page searches for any matches where buildingType and PrimaryCatgeory of card == the current building type and Primary Category selected.
- [ ] onClick of Search on BuildingType view, unrender all the PrimaryCategories and show all of the matched standards (use StandardCardLibrary)

#### Part 2
- [x] The relevant cards are shown accurately on each buildingType and primaryCategory

### Other Notes
- most of what you are going to be working on is on the `server/actions/mongodb/Card` file. More specifically, in the `getCardsPagination` function. See below (both part 1 and 2):
- For part 2, the match query is not working. For this reason, the cards are showing up on all buildingTypes and primaryCategories. Try and find and ideal solution to this. Maybe the `$and` query instead?
<img width="400" alt="image" src="https://user-images.githubusercontent.com/69729390/221374990-4cdce202-adf3-40fb-bc65-091c0a1ccc58.png">
